# Generated by Django 2.2.1 on 2019-05-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW log_level_count
            AS
                SELECT l.level, count(l.*)
                FROM log_log as l
                GROUP BY l.level;
            
            CREATE UNIQUE INDEX log_level ON log_level_count(level);
            """
        )
    ]
