# Generated by Django 2.2.1 on 2019-05-13 06:38

from django.db import migrations
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_create_materialized_view'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.RunSQL(
            """
            CREATE INDEX log_message_gist ON log_log USING GIST (message);
            """
        )
    ]
